기본 DB
+
create table OE1TNPROCESS  (
   OPER_IMPRVM_REQUST_ID VARCHAR2(20) NOT NULL REFERENCES OE1TNOPERIMPROVREQ(OPER_IMPRVM_REQUST_ID),                 
   OPER_PROCESS_ID VARCHAR2(20)  not null,
   OPER_PROCESS_CN VARCHAR2(3000),
   OPER_PROCESS_DATE   VARCHAR2(30),
    constraint OE1TNPROCESS_PK primary key (OPER_PROCESS_ID)
);

TRUNCATE TABLE OE1TNPROCESS

alter table OE1TNPROCESS modify(OPER_PROCESS_DATE DATE);

CREATE SEQUENCE OPER_PROCESS_ID   INCREMENT BY 1 START WITH 10000;
